export interface QuestAddresses {
  none: string;
  fishing: string;
  foraging: string;
  // gardening: string;
  gardeningBtcUsdc: string;
  gardeningCrystalAvax: string;
  gardeningCrystalBtc: string;
  gardeningCrystalEth: string;
  gardeningCrystalJewel: string;
  gardeningCrystalKlay: string;
  gardeningCrystalUsdc: string;
  gardeningEthUsdc: string;
  gardeningJadeAvax: string;
  gardeningJadeBtc: string;
  gardeningJadeEth: string;
  gardeningJadeJewel: string;
  gardeningJadeKlay: string;
  gardeningJadeUsdt: string;
  gardeningJewelAvax: string;
  gardeningJewelBtc: string;
  gardeningJewelEth: string;
  gardeningJewelKlay: string;
  gardeningJewelUsdc: string;
  miningGold: string;
  miningLocked: string;
  wishingWell: string;
  strength: string;
  agility: string;
  intelligence: string;
  wisdom: string;
  luck: string;
  dexterity: string;
  vitality: string;
  endurance: string;
}
